name: Deploy React Book App from GitHub to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # Use Node.js 18 or later

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List files after build
        run: ls -R

      - name: Generate Deployment Package
        run: zip -r ApplyMateFrontendNew.zip . -x "node_modules/*" "**.git**" 

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.SECRET_ACCESS_KEY }}"
          application_name: applymate
          environment_name: Applymate-env-1
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: ApplyMateFrontendNew.zip

      - name: Deployed!
        run: echo "App deployed to Elastic Beanstalk"